[profile.default]
src = "src"
out = "out"
libs = ["lib"]

script = 'script'
optimizer = true
optimizer_runs = 999999


ffi = true
fs_permissions = [
  { access='read-write', path='./.resource-metering.csv' },
  { access='read-write', path='./snapshots/' },
  { access='read-write', path='./deployments/' },
  { access='read', path='./deploy-config/' },
  { access='read', path='./periphery-deploy-config/' },
  { access='read', path='./broadcast/' },
  { access='read', path = './out/' },
  { access='write', path='./semver-lock.json' },
  { access='read-write', path='./.testdata/' },
  { access='read', path='./kout-deployment' }
]

[fmt]
line_length=120
multiline_func_header='all'
bracket_spacing=true
wrap_comments=true
